### PR TITLE
Update schedules.py - Change yellow color from #ebcb8b to #faf08c 

### PR DESCRIPTION
**Pull request by vinztheprinze99**
After discussing with @jeertmans, I decided to make a pull request in order to make the yellow color more visible for the user

### CODE REVIEW

**Comment by jeertmans** [comment]
Hello @vinztheprinze99, thanks for the PR! Maybe, for the other maintainers, could you add screenshot with before / after, using the default colors in both cases?

**Comment by vinztheprinze99** [comment]
Hello @jeertmans , Yes of course ! 

This is the original "yellow" color of the App (LINFO2382 - Friday at 8:30 AM) : 

original_color

And the proposed color : 

two

**Comment by SnaKyEyeS** [comment]
I gotta say, I don't like the new color to be honest and prefer the old one by far... Also, I'm not sure what exactly it brings compared to the old...?

FYI, the color palette comes from the [nord theme](https://www.nordtheme.com/)

**Comment by louisna** [comment]
Hi! Thank you for your contribution! However, I agree with @SnaKyEyeS. I don't really see an improvement in the visibility of the card for the user, and the color does not fit well with the (nord) theme.

**Comment by jeertmans** [comment]
Hello @vinztheprinze, I am sorry that your proposition did not pass the approval of every maintainer... That's democracy :-)
Do you have any other comment to add?
Otherwise, can I close this PR and the issue?

**Pull request closed without merging**
