### PR TITLE
Correct typos in french

### PR DESCRIPTION
**Pull request by LouisLabbe**
In the help-fr.json, contribute-fr.json and whatisnew-fr.json files, I have mainly corrected spelling mistakes corresponding to bad spelling agreements or typos. I also redid some punctuation and tried to add consistency in the use of old and new French spelling (e.g., plait and plaît). 
However, I didn't change the sentences's structure, terms in English or anglicisms (e.g., pull requests or bugs), familiar terms (e.g., typos) or capital letters with accents that I didn't think necessary.
In addition, I also noticed that the links to the EPL courses weren't up to date so I modified them (taking into account the reform) and for more consistency I put the English and French versions in the corresponding json files.
Finally, if you have any doubts about some of my modifications, please don't hesitate to come back to me.

### CODE REVIEW

**Comment by SnaKyEyeS** [comment]
Hey ! Thanks for those corrections !

I know @jeertmans  said he would compile the relevant stuff on his computer on his own; but I'm not sure how we can modify the files from your PR direclty (it would require merging first; then compiling afaik). Thus, could you compile the translations yourself ? It's as simple as installing the python dependencies (`pip install -r dev-requirements.txt`) then run:
```bash
pybabel extract -F translations/babel.cfg -k _l -o translations/messages.pot .
pybabel update -i translations/messages.pot -d translations
pybabel compile -d translations
```
From the base directory of the project; then commit & push !
(if you can't do that for any reason don't worry, we'll manage)

**Comment by LouisLabbe** [comment]
Hi @SnaKyEyeS, thanks for the quick answer !

First of all, I would like to know if it's really necessary to recompile the "translations" as I didn't make any changes on that side (no changes in files like messages.po) but only in the static part with json files which don't seem to be related to translations (from my point of view at this moment) ?

Then, to be honest, my version of linux isn't updated for a while and then I didn't build and install the other dependencies that were required for code modification or translation (not in my case I think) as discussed with @jeertmans. But if as you say it's necessary to do this, I have already installed pip on my windows and so I could run these commands if they are the only ones needed (after fixing version dependencies).

**Comment by SnaKyEyeS** [comment]
Wooops, you're right, there's no need to build the .json translations ! (dat consistency tho)

All good on my side then. 

PS: actually, in order to compile the other (pybabel) translations, you just need to install Flask-Babel (`pip install Flask-Babel`) and it should be good.

**Comment by LouisLabbe** [comment]
Unfortunately, the CI Testing seems to fail. What I find strange is that the test for the "WhatIsNew" view, for example, works fine, but it's the backend/test_ade_api.py that fails. The prepare_url function (appearing in the stacktrace) raises an exception "MissingSchema(error); E requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?"
I re-read what I have done (especially the url changes for open source courses) and actively searched to see if my contribution could somehow produce this but I don't see any link. Do you have an idea on this ?

**Comment by SnaKyEyeS** [comment]
Yeah don't worry that's on @jeertmans, he needs to fix some stuff with the way the testing suite handles the request to the API from external PRs. Your PR is good to go, I'll merge it ;)

**Review by SnaKyEyeS — APPROVED** [review]

**Pull request merged**
